name: speed_up_get
description: Package to speed up GetX.
version: 0.0.1
homepage: https://github.com/AndrewPiterov/speed_up_get

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
