name: speed_up_get
description: Package to speed up GetX.
version: 0.0.3
homepage: https://github.com/AndrewPiterov/speed_up_get

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  shouldly: ^0.5.0+1
  given_when_then_unit_test: ^0.0.10
  
flutter:
