name: speed_up_get
description: Package to speed up GetX.
version: 1.0.0
homepage: https://github.com/AndrewPiterov/speed_up_get

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.6
  flutter:
    sdk: flutter
  get: ^4.6.6
  fluent_result: ^8.4.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  shouldly: ^0.5.0
  given_when_then_unit_test: ^0.2.1
  
flutter:
  uses-material-design: true
